
@host  = http://localhost:5249


POST {{host}}/caixas
Content-Type: application/json
Accept: application/json

{
  "numero": 1,
  "descricaoConteudo": "cabos USB, carregadores antigos, mouse sem fio e adaptadores"
}

###

POST {{host}}/caixas
Content-Type: application/json
Accept: application/json

{
  "numero": 3,
  "descricaoConteudo": "carregador do notebook Dell, fonte de celular, HDMI e teclado reserva"
}

###

POST {{host}}/caixas/localizar
Content-Type: application/json
Accept: application/json

{
  "itemProcurado": "carregador do notebook"
}

###